name: GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *" # Runs every 24 hours
  push:
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_contributors: yes
          plugin_stars: yes
          plugin_followup: yes
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_url: "https://github.com/GOPALNAMDEV"
